#!/bin/sh
handler() {
    cd $LAMBDA_TASK_ROOT

    VUS=$(echo "$1" | ./jq -r .Payload)
    ./k6 run --quiet --vus "$VUS" --duration 10s simple.js
    
    cat /tmp/summary.json
}

while true; do
    HEADERS="$(mktemp)"
    EVENT_DATA=$(curl -sS -LD "$HEADERS" "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/next")

    REQUEST_ID=$(grep -Fi Lambda-Runtime-Aws-Request-Id "$HEADERS" | tr -d '[:space:]' | cut -d: -f2)

    RESPONSE=$(handler "$EVENT_DATA")

    curl -sS -X POST "http://${AWS_LAMBDA_RUNTIME_API}/2018-06-01/runtime/invocation/$REQUEST_ID/response" -d "$RESPONSE"
done
